---
spring:
  resources:
    cache:
      cachecontrol:
        no-cache: true
        no-store: true
    static-locations: "file:./app"
---
cds:
  odata-v4.endpoint.path: "/srv-api/odata/v4"
  security:
    mock:
      enabled: true
      users:
        - name: admin
          password: 1234
          roles:
          - SysAdmin
          attributes:
            { country : KR, language : KO, type : Employee, mail : admin@test.com, display_name : Admin }
        - name: user
          password: 3333
          roles:
          - View
          attributes:
            { country : KR, language : KO, type : Employee, mail : user@test.com, display_name : user }
---
spring:
  profiles: cloud